package admin;

public class dashboard extends javax.swing.JFrame {

  
    public dashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntreatment = new javax.swing.JButton();
        btnproduk = new javax.swing.JButton();
        btnsupplier = new javax.swing.JButton();
        btnpembelian = new javax.swing.JButton();
        btnmembership = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnpegawai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btntreatment.png"))); // NOI18N
        btntreatment.setContentAreaFilled(false);
        btntreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgtreatment.png"))); // NOI18N
        btntreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntreatmentActionPerformed(evt);
            }
        });
        getContentPane().add(btntreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        btntreatment.setBorderPainted(false);

        btnproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnproduk.png"))); // NOI18N
        btnproduk.setContentAreaFilled(false);
        btnproduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgproduk.png"))); // NOI18N
        btnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodukActionPerformed(evt);
            }
        });
        getContentPane().add(btnproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        btnproduk.setBorderPainted(false);

        btnsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnsupplier.png"))); // NOI18N
        btnsupplier.setContentAreaFilled(false);
        btnsupplier.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgsupplier.png"))); // NOI18N
        btnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        btnsupplier.setBorderPainted(false);

        btnpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnpembelian.png"))); // NOI18N
        btnpembelian.setContentAreaFilled(false);
        btnpembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgpembelian.png"))); // NOI18N
        getContentPane().add(btnpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        btnpembelian.setContentAreaFilled(false);

        btnmembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnmembership.png"))); // NOI18N
        btnmembership.setContentAreaFilled(false);
        btnmembership.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgmembership.png"))); // NOI18N
        getContentPane().add(btnmembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        btnmembership.setContentAreaFilled(false);

        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnlaporan.png"))); // NOI18N
        btnlaporan.setContentAreaFilled(false);
        btnlaporan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bglaporan.png"))); // NOI18N
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));
        btnlaporan.setContentAreaFilled(false);

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back.png"))); // NOI18N
        btnlogout.setContentAreaFilled(false);
        btnlogout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back1.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 870, -1, -1));
        btnlogout.setBorderPainted(false);

        btnpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnpegawai.png"))); // NOI18N
        btnpegawai.setContentAreaFilled(false);
        btnpegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/bgpegawai.png"))); // NOI18N
        getContentPane().add(btnpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));
        btnpegawai.setBorderPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntreatmentActionPerformed
        new treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntreatmentActionPerformed

    private void btnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodukActionPerformed
        new produk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnprodukActionPerformed

    private void btnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsupplierActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        new laporan1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale", "1");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmembership;
    private javax.swing.JButton btnpegawai;
    private javax.swing.JButton btnpembelian;
    private javax.swing.JButton btnproduk;
    private javax.swing.JButton btnsupplier;
    private javax.swing.JButton btntreatment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
