import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.plot.PlotOrientation;


/**
 *
 * @author MEGA GLOBAL GRUP
 */
public class owner_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Owner
     */
    public owner_dashboard() {
        initComponents();
        initChart();
        setupButtonActions();
    }

    private void initChart() {
    DefaultCategoryDataset dataset = getTransactionData();
    
    JFreeChart chart = ChartFactory.createBarChart(
        "Transaksi Bulanan Dinda Salon", 
        "Bulan",                          
        "Jumlah Transaksi",               
        dataset,                      
        PlotOrientation.VERTICAL,        
        true,                            
        true,                             
        false                            
    );
    
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560, 370));
    
    // Tambahkan chart dengan AbsoluteConstraints
    this.getContentPane().add(chartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 560, 370));
}
    
    private DefaultCategoryDataset getTransactionData() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        // Koneksi ke database
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String username = "root"; // Ganti dengan username database Anda
        String password = "";     // Ganti dengan password database Anda
        
        try (Connection conn = DriverManager.getConnection(url, username, password)) {
            // Query untuk mendapatkan jumlah transaksi per bulan
            String sql = "SELECT MONTH(tgl_transaksi) as bulan, COUNT(*) as jumlah " +
                         "FROM transaksi " +
                         "GROUP BY MONTH(tgl_transaksi) " +
                         "ORDER BY MONTH(tgl_transaksi)";
            
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                int bulan = rs.getInt("bulan");
                int jumlah = rs.getInt("jumlah");
                
                // Konversi angka bulan ke nama bulan
                String namaBulan = getNamaBulan(bulan);
                dataset.addValue(jumlah, "Transaksi", namaBulan);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error koneksi database: " + e.getMessage());
        }
        
        return dataset;
    }
    
    private String getNamaBulan(int bulan) {
        String[] namaBulan = {
            "Januari", "Februari", "Maret", "April", "Mei", "Juni",
            "Juli", "Agustus", "September", "Oktober", "November", "Desember"
        };
        return (bulan >= 1 && bulan <= 12) ? namaBulan[bulan-1] : "Bulan Tidak Valid";
    }
    
     private void setupButtonActions() {
        btnmembership.addActionListener(e -> {
            new owner_membership().setVisible(true);
            this.dispose();
        });
        
        btnkembali.addActionListener(e -> {
            // For back button - you can customize this
            System.exit(0); // Currently exits application
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmembership = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 104.png"))); // NOI18N
        btnmembership.setContentAreaFilled(false);
        btnmembership.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/Group 104 (1).png"))); // NOI18N
        btnmembership.setBorderPainted(false);
        btnmembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmembershipActionPerformed(evt);
            }
        });
        getContentPane().add(btnmembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/bck.png"))); // NOI18N
        btnkembali.setContentAreaFilled(false);
        btnkembali.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/btn/bck1.png"))); // NOI18N
        btnkembali.setBorderPainted(false);
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 80, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 720, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Group 90.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmembershipActionPerformed
        // TODO add your handling code here:
        owner_membership membershipForm = new owner_membership();
        membershipForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmembershipActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(owner_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new owner_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnmembership;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
