package BaseApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Laporan2 extends javax.swing.JFrame {
    
    DefaultTableModel modelPembelian;
    DefaultTableModel modelTransaksi;

    public Laporan2(LocalDate start, LocalDate end) {
    
    initComponents();
    setLocationRelativeTo(null);
    
    
    
    modelPembelian = new DefaultTableModel(
    new String[]{"ID Beli", "Nama User", "Tanggal Beli", "Total Beli"}, 0);
    modelTransaksi = new DefaultTableModel(
    new String[]{"ID Transaksi", "Nama User", "Tanggal Transaksi", "Total Transaksi"}, 0);

    // SET model ke tabel
    tbl_pembelian.setModel(modelPembelian);
    tbl_transaksi.setModel(modelTransaksi);
    
    tampilkanData(start, end);
    }
    
    private void tampilkanData(LocalDate start, LocalDate end) {
    modelPembelian.setRowCount(0);
    modelTransaksi.setRowCount(0);
    tbl_pembelian.setRowHeight(27);
    tbl_transaksi.setRowHeight(27);

    java.sql.Date sqlStart = java.sql.Date.valueOf(start);
    java.sql.Date sqlEnd   = java.sql.Date.valueOf(end);
    double totalBeli = 0, totalTrans = 0;

    try (Connection con = DriverManager.getConnection(
             "jdbc:mysql://localhost:3306/dinda_salon", "root", "")) {

        // === Pembelian ===
        String sqlBeli = 
          "SELECT p.id_beli, u.nama_user, p.tgl_beli, p.total_beli " +
          "FROM pembelian p JOIN user u ON p.id_user = u.id_user " +
          "WHERE p.tgl_beli BETWEEN ? AND ?";
        PreparedStatement ps1 = con.prepareStatement(sqlBeli);
        ps1.setDate(1, sqlStart);
        ps1.setDate(2, sqlEnd);
        ResultSet rs1 = ps1.executeQuery();
        while (rs1.next()) {
            modelPembelian.addRow(new Object[]{
                rs1.getString("id_beli"),
                rs1.getString("nama_user"),
                rs1.getDate("tgl_beli"),
                rs1.getDouble("total_beli")
            });
            totalBeli += rs1.getDouble("total_beli");
        }
        rs1.close();
        ps1.close();

        // === Transaksi ===
        String sqlTrans = 
          "SELECT t.id_transaksi, u.nama_user, t.tgl_transaksi, t.total_transaksi " +
          "FROM transaksi t JOIN user u ON t.id_user = u.id_user " +
          "WHERE t.tgl_transaksi BETWEEN ? AND ?";
        PreparedStatement ps2 = con.prepareStatement(sqlTrans);
        ps2.setDate(1, sqlStart);
        ps2.setDate(2, sqlEnd);
        ResultSet rs2 = ps2.executeQuery();
        while (rs2.next()) {
            modelTransaksi.addRow(new Object[]{
                rs2.getString("id_transaksi"),
                rs2.getString("nama_user"),
                rs2.getDate("tgl_transaksi"),
                rs2.getDouble("total_transaksi")
            });
            totalTrans += rs2.getDouble("total_transaksi");
        }
        rs2.close();
        ps2.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "DB error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    // Update label untung/rugi
    double hasil = totalTrans - totalBeli;
    String status = hasil >= 0 ? "UNTUNG" : "RUGI";
    penjelasan.setText(String.format(
        "<html>Total Transaksi: Rp%.2f<br>Total Pembelian: Rp%.2f<br>" +
        "<b>Selisih: Rp%.2f (%s)</b></html>",
        totalTrans, totalBeli, hasil, status
    ));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btntreatment = new javax.swing.JButton();
        btnproduk = new javax.swing.JButton();
        btnsupplier = new javax.swing.JButton();
        btnpembelian = new javax.swing.JButton();
        btnmembership = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnpegawai = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pembelian = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        penjelasan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btntreatment.png"))); // NOI18N
        btntreatment.setContentAreaFilled(false);
        btntreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgtreatment.png"))); // NOI18N
        btntreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntreatmentActionPerformed(evt);
            }
        });
        jPanel1.add(btntreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));
        btntreatment.setBorderPainted(false);

        btnproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnproduk.png"))); // NOI18N
        btnproduk.setContentAreaFilled(false);
        btnproduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgproduk.png"))); // NOI18N
        btnproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodukActionPerformed(evt);
            }
        });
        jPanel1.add(btnproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));
        btnproduk.setBorderPainted(false);

        btnsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnsupplier.png"))); // NOI18N
        btnsupplier.setContentAreaFilled(false);
        btnsupplier.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgsupplier.png"))); // NOI18N
        btnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btnsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));
        btnsupplier.setBorderPainted(false);

        btnpembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnpembelian.png"))); // NOI18N
        btnpembelian.setContentAreaFilled(false);
        btnpembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgpembelian.png"))); // NOI18N
        btnpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btnpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, -1));
        btnpembelian.setContentAreaFilled(false);

        btnmembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnmembership.png"))); // NOI18N
        btnmembership.setContentAreaFilled(false);
        btnmembership.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgmembership.png"))); // NOI18N
        btnmembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmembershipActionPerformed(evt);
            }
        });
        jPanel1.add(btnmembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, -1));
        btnmembership.setContentAreaFilled(false);

        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnlaporan.png"))); // NOI18N
        btnlaporan.setContentAreaFilled(false);
        btnlaporan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bglaporan.png"))); // NOI18N
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, -1));
        btnlaporan.setContentAreaFilled(false);

        btnpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/btnpegawai.png"))); // NOI18N
        btnpegawai.setContentAreaFilled(false);
        btnpegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgpegawai.png"))); // NOI18N
        btnpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpegawaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, -1));
        btnpegawai.setBorderPainted(false);

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        btnlogout.setContentAreaFilled(false);
        btnlogout.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back1.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 880, 90, -1));
        btnlogout.setBorderPainted(false);

        tbl_pembelian.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tbl_pembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama User", "Tanggal Beli", "Total Beli"
            }
        ));
        jScrollPane1.setViewportView(tbl_pembelian);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 1070, 260));

        tbl_transaksi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama User", "Tanggal Transaksi", "Total Transaksi"
            }
        ));
        jScrollPane2.setViewportView(tbl_transaksi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 1060, 250));

        penjelasan.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        penjelasan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(penjelasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 800, 1060, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/laporan 2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntreatmentActionPerformed
        new TreatmentAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btntreatmentActionPerformed

    private void btnprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodukActionPerformed
        new ProdukAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnprodukActionPerformed

    private void btnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupplierActionPerformed
        // TODO add your handling code here:
        new SupplierAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsupplierActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        new Laporan1().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        new DashboardAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpembelianActionPerformed
        // TODO add your handling code here:
        new PembelianAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnpembelianActionPerformed

    private void btnmembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmembershipActionPerformed
        // TODO add your handling code here:
        new MembershipAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnmembershipActionPerformed

    private void btnpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpegawaiActionPerformed

    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale", "1");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocalDate end = LocalDate.now();
                LocalDate start = end.minusDays(7);
                new Laporan2(start, end).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlaporan;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmembership;
    private javax.swing.JButton btnpegawai;
    private javax.swing.JButton btnpembelian;
    private javax.swing.JButton btnproduk;
    private javax.swing.JButton btnsupplier;
    private javax.swing.JButton btntreatment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel penjelasan;
    private javax.swing.JTable tbl_pembelian;
    private javax.swing.JTable tbl_transaksi;
    // End of variables declaration//GEN-END:variables
}
