/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import path.KartuMember;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import path.KartuMember;

/**
 *
 * @author ASUS
 */
public class MemberKasir extends javax.swing.JFrame {

    /**
     * Creates new form MemberKasir
     */
    public MemberKasir() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            LoadData();
            generateIdMemberDanRFID();
        } catch (Exception e) {
            e.printStackTrace();
        }
        // Buat combobox supplier transparan 
        cmbx_jekel.setOpaque(false);
        cmbx_jekel.setBackground(new Color(0, 0, 0, 0));
        cmbx_jekel.setForeground(Color.WHITE);
        cmbx_jekel.setBorder(null);
        //buat dropdown transparan combo box supplier
        cmbx_jekel.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value,
                                                          int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (c instanceof JComponent) {
                    ((JComponent) c).setOpaque(false);
                }
                return c;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBTN = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnTreatment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_member = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        text_rfid = new javax.swing.JTextField();
        text_alamat = new javax.swing.JTextField();
        text_notelp = new javax.swing.JTextField();
        text_nama = new javax.swing.JTextField();
        text_idMem = new javax.swing.JTextField();
        cmbx_jekel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(936, 666));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back100.png"))); // NOI18N
        backBTN.setBorder(null);
        backBTN.setContentAreaFilled(false);
        backBTN.setBorderPainted(false);
        backBTN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back50.png"))); // NOI18N
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 570, 73, 70));

        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership100.png"))); // NOI18N
        btnMember.setBorder(null);
        btnMember.setContentAreaFilled(false);
        btnMember.setBorderPainted(false);
        btnMember.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership50.png"))); // NOI18N
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
        jPanel1.add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 290, 73, 70));

        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi100.png"))); // NOI18N
        btnTransaksi.setBorder(null);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi50.png"))); // NOI18N
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 73, 70));

        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian100.png"))); // NOI18N
        btnPembelian.setBorder(null);
        btnPembelian.setBorderPainted(false);
        btnPembelian.setContentAreaFilled(false);
        btnPembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian50.png"))); // NOI18N
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });
        jPanel1.add(btnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 73, 70));

        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk100.png"))); // NOI18N
        btnProduct.setBorder(null);
        btnProduct.setContentAreaFilled(false);
        btnProduct.setBorderPainted(false);
        btnProduct.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk50.png"))); // NOI18N
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        jPanel1.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 73, 70));

        btnTreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment100.png"))); // NOI18N
        btnTreatment.setBorder(null);
        btnTreatment.setContentAreaFilled(false);
        btnTreatment.setBorderPainted(false);
        btnTreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment50.png"))); // NOI18N
        btnTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatmentActionPerformed(evt);
            }
        });
        jPanel1.add(btnTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 73, 70));

        tb_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama ", "Jenis Kelamin", "No. Telp", "Alamat", "RF ID"
            }
        ));
        jScrollPane1.setViewportView(tb_member);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 320));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/simpan100.png"))); // NOI18N
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setBorderPainted(false);
        btn_simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/simpan50.png"))); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 340, 70));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print100.png"))); // NOI18N
        btnPrint.setContentAreaFilled(false);
        btnPrint.setBorderPainted(false);
        btnPrint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print50.png"))); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        btnHapus.setContentAreaFilled(false);
        btnHapus.setBorderPainted(false);
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/hapus100.png"))); // NOI18N
        btnHapus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/hapus50.png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        text_rfid.setBorder(null);
        text_rfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_rfidActionPerformed(evt);
            }
        });
        jPanel1.add(text_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 507, 270, 20));

        text_alamat.setBorder(null);
        jPanel1.add(text_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 446, 270, 20));

        text_notelp.setBorder(null);
        jPanel1.add(text_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 386, 270, 20));

        text_nama.setBorder(null);
        jPanel1.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 270, 20));

        text_idMem.setEditable(false);
        text_idMem.setBorder(null);
        text_idMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idMemActionPerformed(evt);
            }
        });
        jPanel1.add(text_idMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 270, 20));

        cmbx_jekel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jekel", "Perempuan", "Laki-laki" }));
        jPanel1.add(cmbx_jekel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designKasir/Membership.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentActionPerformed
        TreatmentKasir abal = new TreatmentKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTreatmentActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        ProductKasir abal = new ProductKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        PembelianKasir abal = new PembelianKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        TransaksiKasir abal = new TransaksiKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        MemberKasir abal = new MemberKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        btn_simpan.addActionListener(e -> simpanData());
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void text_idMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idMemActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // Ambil baris yang dipilih dari tabel
        int selectedRow = tb_member.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih member untuk dicetak!");
            return;
        }

        // Ambil data dari baris yang dipilih
        DefaultTableModel model = (DefaultTableModel) tb_member.getModel();
        String namaMem = model.getValueAt(selectedRow, 0).toString();
        String rfidCode = model.getValueAt(selectedRow, 4).toString();

        // Cetak kartu
        KartuMember.cetakKartu(namaMem, rfidCode);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void text_rfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_rfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_rfidActionPerformed

    //generate id dan rfid
    private void generateIdMemberDanRFID() {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery("SELECT MAX(id_member) AS max_id FROM member");

            String newId = "M0001";

            if (rs.next()) {
                String maxId = rs.getString("max_id");

                // Generate ID Member (M0001, M0002, ...)
                if (maxId != null && maxId.startsWith("M")) {
                    int num = Integer.parseInt(maxId.substring(1)) + 1;
                    newId = String.format("M%04d", num);
                }
            }

            text_idMem.setText(newId);

            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal generate ID: " + e.getMessage());
        }
    }

    private void simpanData(){
        String Id, Nama_Pelanggan, Jekel, No_Telp, Alamat, rfid, query;
        int poin;

        Nama_Pelanggan = text_nama.getText();
        No_Telp = text_notelp.getText();
        Alamat = text_alamat.getText();
        Id = text_idMem.getText();
        Jekel = cmbx_jekel.getSelectedItem().toString();
        poin = 0;
        rfid = text_rfid.getText();

        query = "insert into member (id_member, nama_member, jenis_kelamin, notelp_member, alamat_member, poin_member, rfID) values(?, ?, ?, ?, ?, ?, ?)";

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
            PreparedStatement s = conn.prepareStatement(query);
            s.setString(1, Id);
            s.setString(2, Nama_Pelanggan);
            s.setString(3, Jekel);
            s.setString(4, No_Telp);
            s.setString(5, Alamat);
            s.setInt(6, poin);
            s.setString(7, rfid);

        int result = s.executeUpdate();

            if (result > 0 ) {
                    JOptionPane.showMessageDialog(new JFrame(), "Yeay! pelanggan telah ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Yahh gagal nih, coba lagi ya!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                conn.close();

            text_nama.setText("");
            text_notelp.setText("");
            text_alamat.setText("");
            text_idMem.setText("");
            text_rfid.setText("");
            cmbx_jekel.setSelectedIndex(0);

            LoadData();
            generateIdMemberDanRFID();
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "Database Error" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    public void LoadData() throws java.sql.SQLException {
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";
        String Query = "SELECT nama_member, jenis_kelamin, notelp_member, alamat_member, rfID FROM member";
        
        try {
            Connection connect = java.sql.DriverManager.getConnection(url, user, pw);
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(Query);
            
            DefaultTableModel model = (DefaultTableModel) tb_member.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {                
                Object[] row = {
                rs.getString("nama_member"),
                rs.getString("jenis_kelamin"),
                rs.getString("notelp_member"),
                rs.getString("alamat_member"),
                rs.getString("rfID")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data tidak bisa tampil! Error: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnTreatment;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cmbx_jekel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_member;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_idMem;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_notelp;
    private javax.swing.JTextField text_rfid;
    // End of variables declaration//GEN-END:variables
}
