/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author ASUS
 */
public class SignIn extends javax.swing.JFrame {
    public static String LoggedInUser;
    public static String LoggedNameUser;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_SignIn = new javax.swing.JButton();
        btn_signUp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ck_show = new javax.swing.JCheckBox();
        txt_password = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(936, 666));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_SignIn.setContentAreaFilled(false);
        btn_SignIn.setBorderPainted(false);
        btn_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/signIn100.png"))); // NOI18N
        btn_SignIn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/signIn50.png"))); // NOI18N
        btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignInActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 200, 60));

        btn_signUp.setContentAreaFilled(false);
        btn_signUp.setBorderPainted(false);
        btn_signUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Sign Up100.png"))); // NOI18N
        btn_signUp.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Sign Up50.png"))); // NOI18N
        jPanel1.add(btn_signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 515, -1, 20));

        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back100.png"))); // NOI18N
        btnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back50.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 80, 70));

        ck_show.setOpaque(false);
        ck_show.setBorder(null);
        ck_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_showActionPerformed(evt);
            }
        });
        jPanel1.add(ck_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 400, 30, 30));

        txt_password.setBorder(null);
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 460, 30));

        txt_username.setBorder(null);
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 440, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design_/Sign In.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignInActionPerformed
        String usn = txt_username.getText().trim();
        String pw = txt_password.getText().trim();
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pass = "";

        if (usn.isEmpty() || pw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username atau password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection conn = java.sql.DriverManager.getConnection(url, user, pass);
            String query = "SELECT * FROM user WHERE username = ? AND password = ?";

            PreparedStatement s = conn.prepareStatement(query);
            s.setString(1, usn);
            s.setString(2, pw);

            ResultSet rs = s.executeQuery();

            if (rs.next()) {
                // Login berhasil
                int ID = rs.getInt("id_user");
                String nama = rs.getString("nama_user");
                String level = rs.getString("level");

                // Simpan ID dan nama user ke variabel global
                LoggedInUser = String.valueOf(ID);  // <<== penting!
                LoggedNameUser = nama;

                switch (level.toLowerCase()) {
                    case "owner":
                        DashboardOwner abal = new DashboardOwner();
                        abal.setVisible(true);
                        abal.pack();
                        abal.setLocationRelativeTo(null);
                        this.dispose();
                        break;
                    case "admin":
                        DashboardAdmin abal1 = new DashboardAdmin();
                        abal1.setVisible(true);
                        abal1.pack();
                        abal1.setLocationRelativeTo(null);
                        this.dispose();
                        break;
                    case "kasir":
                        DashboardKasir abal2 = new DashboardKasir();
                        abal2.setVisible(true);
                        abal2.pack();
                        abal2.setLocationRelativeTo(null);
                        this.dispose();
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Level tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
             else {
                // Username atau password salah
                JOptionPane.showMessageDialog(this, "Username dan password yang anda masukkan salah", "Error", JOptionPane.ERROR_MESSAGE);
            }

           

        } catch (Exception e) {
            e.printStackTrace(); // untuk debugging
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencoba login", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_SignInActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Login abal2 = new Login();
        abal2.setVisible(true);
        abal2.pack();
        abal2.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void ck_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_showActionPerformed
        if (ck_show.isSelected()) {
            txt_password.setEchoChar((char) 0);
        } else {
            txt_password.setEchoChar('*');
        }
    }//GEN-LAST:event_ck_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_SignIn;
    private javax.swing.JButton btn_signUp;
    private javax.swing.JCheckBox ck_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
