/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.util.ArrayList;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author ASUS
 */
public class TransaksiProduk extends javax.swing.JFrame {
    public static String Id;
    /**
     * Creates new form TransaksiKasir
     */
    public TransaksiProduk() {
        initComponents();
        setLocationRelativeTo(null);
        this.Id = SignIn.LoggedInUser;
        try {
            loadPromo();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Sembunyikan kolom "No." (kolom pertama di tampilan)
            TableColumnModel columnModel = tb_sementara.getColumnModel();
            if (columnModel.getColumnCount() > 0) {
                columnModel.removeColumn(columnModel.getColumn(0)); // Kolom "No."
            }

            
        
        // Tambahkan DocumentListener ke txt_jumlah
        txt_jumlah.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                updateSubtotal();
            }
            public void removeUpdate(DocumentEvent e) {
                updateSubtotal();
            }
            public void changedUpdate(DocumentEvent e) {
                updateSubtotal();
            }
        });
        // Listener untuk scan RFID member saat tekan enter
        txt_rfid.addActionListener(evt -> {
            String rfid = txt_rfid.getText();
            if (!rfid.isEmpty()) {
                cariMemberByRFID(rfid);
            }
        });
        
        //Listener untuk menghitung total
        // Tambahkan TableModelListener ke tb_sementara
        tb_sementara.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                updateTotal();
            }
        });
        
        //Listener txt_bayar
        txt_bayar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               updateKembali();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               updateKembali();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               updateKembali();
            }
        });
        
        //Listener txt_total
        txt_total.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateKembali();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateKembali();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               updateKembali();
            }
        });
        
        // Listener untuk pemilihan diskon
        cmbx_diskon.addActionListener(evt -> updateTotal());
        
        //border dan content filled cmbx false
        cmbx_diskon.setOpaque(false);
        cmbx_diskon.setBackground(new Color(0, 0, 0, 0));
        cmbx_diskon.setForeground(Color.WHITE);
        cmbx_diskon.setBorder(null);
        //buat dropdown transparan combo box supplier
        cmbx_diskon.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value,
                                                          int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (c instanceof JComponent) {
                    ((JComponent) c).setOpaque(false);
                }
                return c;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sementara = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        cmbx_diskon = new javax.swing.JComboBox<>();
        txt_kembali = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_poin = new javax.swing.JTextField();
        txt_rfid = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_namaBarang = new javax.swing.JTextField();
        scan_barcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(936, 666));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setContentAreaFilled(false);
        btnSimpan.setBorderPainted(false);
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 60 (1).png"))); // NOI18N
        btnSimpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 60.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        btnBayar.setContentAreaFilled(false);
        btnBayar.setBorderPainted(false);
        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designKasir/Group 27.png"))); // NOI18N
        btnBayar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 27 (1).png"))); // NOI18N
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back100.png"))); // NOI18N
        btnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back50.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, -1, -1));

        tb_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Kode", "Nama ", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tb_sementara);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 660, 150));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 80.png"))); // NOI18N
        btnHapus.setContentAreaFilled(false);
        btnHapus.setBorderPainted(false);
        btnHapus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 80 (1).png"))); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        cmbx_diskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih promo" }));
        cmbx_diskon.setBorder(null);
        cmbx_diskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_diskonActionPerformed(evt);
            }
        });
        jPanel1.add(cmbx_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 160, 30));

        txt_kembali.setBorder(null);
        txt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 150, 30));

        txt_bayar.setBorder(null);
        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 481, 150, 30));

        txt_total.setBorder(null);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 600, 150, 30));

        txt_poin.setBorder(null);
        txt_poin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_poinActionPerformed(evt);
            }
        });
        jPanel1.add(txt_poin, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 519, 150, 30));

        txt_rfid.setBorder(null);
        txt_rfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rfidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 479, 150, 30));

        txt_jumlah.setBorder(null);
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 71, 150, 30));

        txt_harga.setBorder(null);
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 150, 30));

        txt_subtotal.setBorder(null);
        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 129, 150, 30));

        txt_namaBarang.setBorder(null);
        txt_namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaBarangActionPerformed(evt);
            }
        });
        jPanel1.add(txt_namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 72, 150, 30));

        scan_barcode.setBorder(null);
        scan_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scan_barcodeActionPerformed(evt);
            }
        });
        jPanel1.add(scan_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designKasir/transaksi produk (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new TransaksiKasir().setVisible(true);
        this.dispose();
         JOptionPane.showMessageDialog(this, "Batal melakukan transaksi.", "Batal", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBackActionPerformed

    private void scan_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scan_barcodeActionPerformed
    String kode = scan_barcode.getText();

    // Ambil data produk dari database berdasarkan kode
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
        String sql = "SELECT * FROM produk WHERE barcode = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, kode);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txt_namaBarang.setText(rs.getString("nama_produk"));
            txt_harga.setText(rs.getString("harga_produk"));
            txt_jumlah.requestFocus(); // pindah fokus ke jumlah
        } else {
            JOptionPane.showMessageDialog(this, "Produk tidak ditemukan");
        }

        con.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_scan_barcodeActionPerformed

    private void txt_namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaBarangActionPerformed

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed

    }//GEN-LAST:event_txt_jumlahActionPerformed
    
    private void updateSubtotal() {
        try {
            int harga = Integer.parseInt(txt_harga.getText());
            int jumlah = Integer.parseInt(txt_jumlah.getText());
            int subtotal = harga * jumlah;
            txt_subtotal.setText(String.valueOf(subtotal));
        } catch (NumberFormatException e) {
            // Jika input jumlah kosong atau bukan angka, subtotal dikosongkan atau 0
            txt_subtotal.setText("");
        }
    }

    //method untuk proses perubahan total
    private void updateTotal() {
        int total = 0;
        DefaultTableModel model = (DefaultTableModel) tb_sementara.getModel();

        // Hitung subtotal dari tabel
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (int) model.getValueAt(i, 5); // Mengasumsikan subtotal ada di kolom ke-5
        }
        // Terapkan diskon jika ada
        String selectedItem = (String) cmbx_diskon.getSelectedItem();
        if (selectedItem != null && !selectedItem.equals("Pilih promo")) {
            String[] parts = selectedItem.split(" - ");
            int discountPercentage = getDiscountPercentage(Integer.parseInt(parts[0].trim())); // Ambil ID promo
            total -= (total * discountPercentage / 100);
        }
        // Update txt_total
        txt_total.setText(String.valueOf(total));
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
        String barcode = scan_barcode.getText();
        int jumlah = Integer.parseInt(txt_jumlah.getText());

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");

        // Ambil data produk berdasarkan barcode
        String sqlProduk = "SELECT kd_produk, nama_produk, harga_produk FROM produk WHERE barcode = ?";
        PreparedStatement pstProduk = conn.prepareStatement(sqlProduk);
        pstProduk.setString(1, barcode);
        ResultSet rsProduk = pstProduk.executeQuery();

        if (rsProduk.next()) {
            String kd_produk = rsProduk.getString("kd_produk");
            String nama = rsProduk.getString("nama_produk");
            int harga = rsProduk.getInt("harga_produk");
            int subtotal = harga * jumlah;
            int Layanan = 1;

            // Tampilkan ke form
            txt_namaBarang.setText(nama);
            txt_harga.setText(String.valueOf(harga));
            txt_subtotal.setText(String.valueOf(subtotal));

            // Simpan ke database (tabel detail_sementara)
            String sqlInsert = "INSERT INTO detail_sementara (kd_produk, id_layanan, jumlah_sm, subtotal) VALUES (?, ?, ?, ?)";
            PreparedStatement pstInsert = conn.prepareStatement(sqlInsert, Statement.RETURN_GENERATED_KEYS);
            pstInsert.setString(1, kd_produk);
            pstInsert.setInt(2, Layanan);
            pstInsert.setInt(3, jumlah);
            pstInsert.setInt(4, subtotal);
            pstInsert.executeUpdate();
            
            // Ambil id_sementara yang baru dibuat
            ResultSet generatedKeys = pstInsert.getGeneratedKeys();
            int id_sementara = -1;
            if (generatedKeys.next()) {
                id_sementara = generatedKeys.getInt(1);
            }
            
            
            // Tambahkan ke tabel sementara
            DefaultTableModel model = (DefaultTableModel) tb_sementara.getModel();
            model.addRow(new Object[]{id_sementara, kd_produk, nama, harga, jumlah, subtotal});
            
            scan_barcode.setText("");
            txt_namaBarang.setText("");
            txt_harga.setText("");
            txt_jumlah.setText("");
            txt_subtotal.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Barcode tidak ditemukan di database.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        DefaultTableModel model = (DefaultTableModel) tb_sementara.getModel();
        int selectedRow = tb_sementara.getSelectedRow();

        if (selectedRow >= 0) {
            // Ambil kd_produk dari baris yang dipilih
            String kd_produk = model.getValueAt(selectedRow, 0).toString();

            try {
                // Koneksi database
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");

                // Query hapus data dari detail_sementara berdasarkan kd_produk
                String sqlDelete = "DELETE FROM detail_sementara WHERE kd_produk = ?";
                PreparedStatement pstDelete = conn.prepareStatement(sqlDelete);
                pstDelete.setString(1, kd_produk);

                int affectedRows = pstDelete.executeUpdate();

                if (affectedRows > 0) {
                    // Jika berhasil dihapus dari DB, hapus juga dari tabel
                    model.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan di database.");
                }

                pstDelete.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txt_rfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rfidActionPerformed
    private void cariMemberByRFID(String rfid) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
            String sql = "SELECT * FROM member WHERE rfid = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, rfid);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Contoh kolom member: nama_member, poin_member, diskon_member (persen)
                txt_poin.setText(String.valueOf(rs.getInt("poin_member")));

            } else {
                JOptionPane.showMessageDialog(this, "Member dengan RFID tersebut tidak ditemukan.");
                txt_poin.setText("");
            }

            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }
    private void txt_poinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_poinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_poinActionPerformed

    private void cmbx_diskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_diskonActionPerformed
            try {
            String selectedItem = (String) cmbx_diskon.getSelectedItem();
            if (selectedItem == null || selectedItem.equals("0 - Pilih Promo")) {
                return;
            }
            // Parsing yang lebih robust dari item yang dipilih
            String[] parts = selectedItem.split(" - ", 2);
            if (parts.length < 2) {
                throw new IllegalArgumentException("Format item tidak valid");
            }
            int selectedId = Integer.parseInt(parts[0].trim());
            String selectedName = parts[1].trim();
            // Ambil persentase diskon dari database
            int discountPercentage = getDiscountPercentage(selectedId);

            // Update total setelah memilih promo
            updateTotal();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format ID promo tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmbx_diskonActionPerformed
    
    // Metode untuk mendapatkan persentase diskon dari database
    private int getDiscountPercentage(int promoId) {
        int discount = 0;
        String query = "SELECT diskon FROM promo WHERE id_promo = ?";
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
             PreparedStatement pstmt = conn.prepareStatement(query)) {
            pstmt.setInt(1, promoId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                discount = rs.getInt("diskon");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat mengambil diskon: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return discount;
    }
    
    // Improved supplier loading method
    private void loadPromo() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";
        String query = "SELECT id_promo, jenis_promo FROM promo";

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("0 - Pilih Promo");

        try (Connection conn = DriverManager.getConnection(url, user, pw);
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(query)) {

            while(rs.next()) {
                int id = rs.getInt("id_promo");
                String nama = rs.getString("jenis_promo");
                model.addElement(id + " - " + nama);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Gagal memuat data supplier:\n" + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
            throw e;
        }

        cmbx_diskon.setModel(model);
    }
    //method untuk mengambil id ke combo box
    private int getIdFromComboBox(javax.swing.JComboBox<String> comboBox){
        String selectedItem = (String) comboBox.getSelectedItem();
        if (selectedItem != null && selectedItem.contains(" - ")) {
            String[] parts = selectedItem.split(" - ", 2);
            return Integer.parseInt(parts[0]);
        }
        return 0;
    }
    
    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembaliActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
            try {
            // Validasi agar inputan diisi oleh user
            if (cmbx_diskon.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Harap Pilih Salah Satu!", "ERROR", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Mendapatkan model tabel
            DefaultTableModel model = (DefaultTableModel) tb_sementara.getModel();

            // Membuat list untuk menyimpan data
            List<String[]> listData = new ArrayList<>();

            // Iterasi melalui semua baris di tabel
            for (int i = 0; i < model.getRowCount(); i++) {
                String id_sm = model.getValueAt(i, 0).toString();
                String kd_brg = model.getValueAt(i, 1).toString(); // Kode
                String jumlah = model.getValueAt(i, 4).toString(); // Jumlah
                String subtotal = model.getValueAt(i, 5).toString(); // Subtotal

                // Menyimpan data dalam array
                String[] data = {id_sm, kd_brg, jumlah, subtotal};
                listData.add(data); // Menambahkan array ke list
            }
            
            //pengambilan id member 
            String RF = txt_rfid.getText();
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dinda_salon", "root", "");
            String query = "SELECT id_member FROM member WHERE rfID = ?";
            PreparedStatement stm = conn.prepareStatement(query);
            stm.setString(1, RF);
            ResultSet rs = stm.executeQuery();
            String idmemb = null;
                if (rs.next()) {
                    idmemb = rs.getString("id_member");
                } else{
                    JOptionPane.showMessageDialog(this, "Member tidak ditemukan!", "ERROR", JOptionPane.WARNING_MESSAGE);
                    return;
                }        
            // Proses inisialisasi 
            int diskon = getIdFromComboBox(cmbx_diskon);
            String IdUser  = TransaksiProduk.Id;
            LocalDate tgl_jual = LocalDate.now();
            String total_jual = txt_total.getText();
            String bayar_jual = txt_bayar.getText();
            String kembali_jual = txt_kembali.getText();
            int Layanan = 1;
            
            // Melakukan transaksi untuk setiap item dalam listData
            for (String[] data : listData) {
                String id_sm = data[0]; // Kode barang
                String kd_brg = data[1]; // Kode barang
                String jumlah = data[2]; // Jumlah
                String subtotal = data[3]; // Subtotal

                // Memanggil method lain untuk menyimpan transaksi
                SimpanTransaksi(IdUser, idmemb, diskon, tgl_jual, total_jual, bayar_jual, kembali_jual, kd_brg, jumlah, subtotal, id_sm, Layanan);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "YAHH Gagal melakukan transaksi: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBayarActionPerformed

    //proses untuk simpan transaksi bayar
    private void SimpanTransaksi(String IdUser, String idmemb,int diskon,LocalDate tgl_jual, String total_jual, String bayar_jual, String kembali_jual, String kd_brg, String jumlah, String subtotal, String id_sm, int Layanan){
        Connection conn = null;
        PreparedStatement stmt1 = null;
        PreparedStatement stmt2 = null;
        PreparedStatement stmt3 = null;
        try {
            String url = "jdbc:mysql://localhost:3306/dinda_salon";
            String user = "root";
            String pw = "";
            conn = DriverManager.getConnection(url, user, pw);
            
            //mengaktifkan auto-commit untuk memulai transaksi
            conn.setAutoCommit(false);
            
            //query untuk menambah data ke database
            String insert1 = "INSERT INTO transaksi (id_user, id_member, id_promo, tgl_transaksi, total_transaksi, bayar, kembali) VALUES (?, ?, ?, ?, ?, ?, ?)";
            stmt1 = conn.prepareStatement(insert1, Statement.RETURN_GENERATED_KEYS);
            stmt1.setString(1, IdUser);
            stmt1.setString(2, idmemb);
            stmt1.setInt(3, diskon);
            stmt1.setDate(4, java.sql.Date.valueOf(tgl_jual));
            stmt1.setString(5, total_jual);
            stmt1.setString(6, bayar_jual);
            stmt1.setString(7, kembali_jual);
            
            //eksekusi table pertama
            int afectedrows = stmt1.executeUpdate();
            
            //ambil id transaksi yang baru saja dimasukkan
            int idTrans = 0;
            if (afectedrows > 0) {
                try (ResultSet generatedKeys = stmt1.getGeneratedKeys()){
                    if (generatedKeys.next()) {
                        idTrans = generatedKeys.getInt(1);
                    }
                } 
            }
            
            //jika tidak ada id, maka batalkan transaksi
            if (idTrans == 0) {
                throw new SQLException("Menyimpan transaksi gagal, Id transaksi tidak tersedia!");
            }
            
            //query untuk menambah ke detail pembelian
            String insert2 = "INSERT INTO detail_transaksi (id_detail, id_transaksi,id_layanan, kd_produk, jumlah_jual, subtotal) VALUES (?, ?, ?, ?, ?, ?)";
            stmt2 = conn.prepareStatement(insert2);
            stmt2.setString(1, id_sm);
            stmt2.setInt(2, idTrans);
            stmt2.setInt(3, Layanan);
            stmt2.setString(4, kd_brg);
            stmt2.setString(5, jumlah);
            stmt2.setString(6, subtotal);
            stmt2.executeUpdate();
            
            String hapus = "DELETE FROM detail_sementara WHERE id_sementara = ?";
            stmt3 = conn.prepareStatement(hapus);
            stmt3.setString(1, id_sm);
            
            int result = stmt3.executeUpdate();
            
            //jika kedua query berhasil, commit transaksi
            conn.commit();
            
             if (result > 0) {
            // Tampilkan pesan sukses dan reset form
                JOptionPane.showMessageDialog(this, "Transaksi berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan transaksi. Coba lagi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
             
             new TransaksiKasir().setVisible(true);
             this.dispose();
             
        } catch (Exception e) {
            if (conn != null) {
                try {
                    conn.rollback();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
            JOptionPane.showMessageDialog(null, "Gagal menyimpan transaksi: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                if (stmt1 != null) stmt1.close();
                if (stmt2 != null) stmt2.close();
                if (stmt3 != null) stmt3.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    //proses untuk isi kembali otomatis
    private void updateKembali(){
        try {
            int total = Integer.parseInt(txt_total.getText());
            int bayar = Integer.parseInt(txt_bayar.getText());
            int kembali = bayar - total;
            
            //memastikan nilai nya tida negatif
            if (kembali < 0) {
                txt_kembali.setText("0");
            }else{
                txt_kembali.setText(String.valueOf(kembali));
            }
        } catch (Exception e) {
            //jika inputan bayar kosong
            txt_kembali.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbx_diskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scan_barcode;
    private javax.swing.JTable tb_sementara;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_namaBarang;
    private javax.swing.JTextField txt_poin;
    private javax.swing.JTextField txt_rfid;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
