/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Base;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author ASUS
 */
public class TransaksiKasir extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentKasir
     */
    public TransaksiKasir() {
        initComponents();
        setLocationRelativeTo(null);
        // Sembunyikan kolom "No." (kolom pertama di tampilan)
            TableColumnModel columnModel = tb_transaksi.getColumnModel();
            if (columnModel.getColumnCount() > 0) {
                columnModel.removeColumn(columnModel.getColumn(0)); // Kolom "No."
            }
        try {
            LoadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak berhasil tampil! Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnLayanan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnMember = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnTreatment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_transaksi = new javax.swing.JTable();
        btnProduk = new javax.swing.JButton();
        labelTrans = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(936, 666));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setContentAreaFilled(false);
        btnPrint.setBorderPainted(false);
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print100.png"))); // NOI18N
        btnPrint.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/print50.png"))); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, -1));

        btnLayanan.setContentAreaFilled(false);
        btnLayanan.setBorderPainted(false);
        btnLayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 75.png"))); // NOI18N
        btnLayanan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 75 (1).png"))); // NOI18N
        btnLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayananActionPerformed(evt);
            }
        });
        jPanel2.add(btnLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back100.png"))); // NOI18N
        btnBack.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/back50.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 580, 73, 70));

        btnMember.setContentAreaFilled(false);
        btnMember.setBorderPainted(false);
        btnMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership100.png"))); // NOI18N
        btnMember.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnMembership50.png"))); // NOI18N
        btnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemberActionPerformed(evt);
            }
        });
        jPanel2.add(btnMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 290, 73, 70));

        btnTransaksi.setBorderPainted(false);
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi100.png"))); // NOI18N
        btnTransaksi.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTransaksi50.png"))); // NOI18N
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 73, 70));

        btnPembelian.setBorderPainted(false);
        btnPembelian.setContentAreaFilled(false);
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian100.png"))); // NOI18N
        btnPembelian.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnPembelian50.png"))); // NOI18N
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });
        jPanel2.add(btnPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 150, 73, 70));

        btnProduct.setBorderPainted(false);
        btnProduct.setContentAreaFilled(false);
        btnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk100.png"))); // NOI18N
        btnProduct.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnProduk50.png"))); // NOI18N
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 73, 70));

        btnTreatment.setBorderPainted(false);
        btnTreatment.setContentAreaFilled(false);
        btnTreatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment100.png"))); // NOI18N
        btnTreatment.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/btnTreatment50.png"))); // NOI18N
        btnTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatmentActionPerformed(evt);
            }
        });
        jPanel2.add(btnTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 73, 70));

        tb_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idDetail", "Member", "Produk", "Layanan", "Tanggal", "Jumlah", "Subtotal", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_transaksi);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 740, 380));

        btnProduk.setContentAreaFilled(false);
        btnProduk.setBorderPainted(false);
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 74.png"))); // NOI18N
        btnProduk.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button/Group 74 (1).png"))); // NOI18N
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        labelTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/designKasir/transaksi (1).png"))); // NOI18N
        jPanel2.add(labelTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentActionPerformed
        TransaksiKasir abal = new TransaksiKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTreatmentActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        ProductKasir abal = new ProductKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        PembelianKasir abal = new PembelianKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        TransaksiKasir abal = new TransaksiKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemberActionPerformed
        MemberKasir abal = new MemberKasir();
        abal.setVisible(true);
        abal.pack();
        abal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMemberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardKasir().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        new TransaksiProduk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayananActionPerformed
        new TransaksiLayanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLayananActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        int selectedRow = tb_transaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi untuk dicetak!");
            return;
        }

        String idDetail = tb_transaksi.getModel().getValueAt(selectedRow, 0).toString();
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";

        try {
            Connection conn = DriverManager.getConnection(url, user, pw);

            // Ambil id_transaksi dari id_detail
            String getIdTransQuery = "SELECT id_transaksi FROM vjual WHERE id_detail = ?";
            java.sql.PreparedStatement getIdTransStm = conn.prepareStatement(getIdTransQuery);
            getIdTransStm.setString(1, idDetail);
            java.sql.ResultSet rsTrans = getIdTransStm.executeQuery();

            if (!rsTrans.next()) {
                JOptionPane.showMessageDialog(this, "Data transaksi tidak ditemukan.");
                return;
            }

            String idTransaksi = rsTrans.getString("id_transaksi");

            // Ambil semua detail untuk transaksi tersebut
            String query = "SELECT * FROM vjual WHERE id_transaksi = ?";
            java.sql.PreparedStatement stm = conn.prepareStatement(query);
            stm.setString(1, idTransaksi);
            java.sql.ResultSet rs = stm.executeQuery();

            String namaKasir = "", namaMember = "", tanggal = "", total = "", bayar = "", kembali = "";
            List<String> produkList = new ArrayList<>();
            List<String> layananList = new ArrayList<>();

            while (rs.next()) {
                namaMember = rs.getString("nama_member");
                namaKasir = rs.getString("nama_user");
                tanggal = rs.getString("tgl_transaksi");
                total = rs.getString("total_transaksi");
                bayar = rs.getString("bayar");
                kembali = rs.getString("kembali");

                String namaLayanan = rs.getString("nama_layanan");
                int jumlah = rs.getInt("jumlah_jual");
                int subtotal = rs.getInt("subtotal");

                String idLayanan = rs.getString("id_layanan");
                String kdProduk = rs.getString("kd_produk");

                if (!"P000000".equals(kdProduk)) {
                    // Ini produk valid
                    produkList.add(String.format("%s x%d - Rp%,d", namaLayanan, jumlah, subtotal));
                } else if (!"1".equals(idLayanan)) {
                    // Ini layanan valid
                    layananList.add(String.format("%s x%d - Rp%,d", namaLayanan, jumlah, subtotal));
                }
            }


            // Path ke logo (ubah sesuai lokasi Anda)
            String logoPath = new File("src/design_/Logo1.png").toURI().toURL().toString();

            // HTML Template
            StringBuilder html = new StringBuilder();
            html.append("<html><body style='font-family:monospace;'>");
            html.append("<div style='text-align:center;'>");
            html.append("<img src='").append(logoPath).append("' width='100'/><br/>");
            html.append("<b style='font-size:14pt;'>DINDA SALON</b><br/>");
            html.append("Jl. Gajah Mada - Garut<br/>");
            html.append("Telp: 0812 3456 7890<br/>");
            html.append("</div><hr/>");
            html.append("<b>No Transaksi :</b> ").append(idTransaksi).append("<br/>");
            html.append("<b>Tanggal      :</b> ").append(tanggal).append("<br/>");
            html.append("<b>Pelanggan    :</b> ").append(namaMember).append("<br/>");
            html.append("<b>Kasir        :</b> ").append(namaKasir).append("<br/>");
            html.append("<hr/>");

            // Jika ada produk, tampilkan bagian Produk
            if (!produkList.isEmpty()) {
                html.append("<b>Produk:</b><br/>");
                for (String item : produkList) {
                    html.append(item).append("<br/>");
                }
            }

            // Jika ada layanan, tampilkan bagian Layanan
            if (!layananList.isEmpty()) {
                html.append("<b>Layanan:</b><br/>");
                for (String item : layananList) {
                    html.append(item).append("<br/>");
                }
            }

            html.append("<hr/>");
            html.append(String.format("<b>Total    :</b> Rp%,d<br/>", Integer.parseInt(total)));
            html.append(String.format("<b>Bayar    :</b> Rp%,d<br/>", Integer.parseInt(bayar)));
            html.append(String.format("<b>Kembali  :</b> Rp%,d<br/>", Integer.parseInt(kembali)));
            html.append("<hr/>");
            html.append("<center>Terima kasih atas kunjungan Anda<br/>www.dindasalon.com</center>");
            html.append("</body></html>");


            // Tampilkan & cetak HTML struk
            JTextPane pane = new JTextPane();
            pane.setContentType("text/html");
            pane.setText(html.toString());
            pane.setEditable(false);
            pane.print();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed
    public void LoadData() throws java.sql.SQLException {
        String url = "jdbc:mysql://localhost:3306/dinda_salon";
        String user = "root";
        String pw = "";
        String Query = "SELECT id_detail, nama_member, nama_layanan, nama_produk, tgl_transaksi, jumlah_jual, subtotal, total_transaksi FROM vJual ORDER BY tgl_transaksi DESC";
        
        try {
            Connection connect = java.sql.DriverManager.getConnection(url, user, pw);
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(Query);
            
            DefaultTableModel model = (DefaultTableModel) tb_transaksi.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {                
                Object[] row = {
                rs.getString("id_detail"),
                rs.getString("nama_member"),
                rs.getString("nama_layanan"),
                rs.getString("nama_produk"),
                rs.getString("tgl_transaksi"),
                rs.getString("jumlah_jual"),
                rs.getString("subtotal"),
                rs.getString("total_transaksi")
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data tidak bisa tampil! Error: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLayanan;
    private javax.swing.JButton btnMember;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnProduk;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnTreatment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTrans;
    private javax.swing.JTable tb_transaksi;
    // End of variables declaration//GEN-END:variables
}
